# thank you to https://github.com/mjhwully for cap-add trick : https://github.com/MatthewVance/unbound-docker-rpi/issues/4
services:
  unbound:
    build: .
    network_mode: host
    cap_add: 
      - NET_ADMIN
    volumes:
      - ./conf:/conf
      - ./log:/usr/local/etc/unbound/log
    restart: unless-stopped
    command: unbound -d -c /conf/localhost.conf
